services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  master_node:
    build:
      context: .
      dockerfile: master.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - WORKER_NODES=${WORKER_NODES}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
    depends_on:
      - mysql
      - worker_node1
      - worker_node2
      - worker_node3

  worker_node1:
    build:
      context: .
      dockerfile: worker.Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PORT=${PORT}

  worker_node2:
    build:
      context: .
      dockerfile: worker.Dockerfile
    ports:
      - "8082:8080"
    environment:
      - PORT=${PORT}

  worker_node3:
    build:
      context: .
      dockerfile: worker.Dockerfile
    ports:
      - "8083:8080"
    environment:
      - PORT=${PORT}